### PR TITLE
to_param when we have no slug

### PR DESCRIPTION
**Pull request by DonSchado**
Remember when we needed to ask in the places view if `slug.nil?`, to avoid the scary exception? 
Today we learn how to deal with this more gracefully (so it's not needed in the view), and more important "repair" the place data directly in case of an error. 

some resources, in case you get stuck: 
- http://www.mikeperham.com/2012/03/03/the-perils-of-rescue-exception/
- http://www.rubyinside.com/21-ruby-tricks-902.html

Have fun!

### CODE REVIEW

**Comment by erdnusskeks** [comment]
Hej Marco!
Danke für die neue Herausforderung! : )

Aber wenn ich rake im Terminal eingebe, erscheint das hier:
Could not find psych-2.0.1 in any of the sources
Run `bundle install` to install missing gems.

Wenn ich bundle install bzw. bundle install psych-2.0.1 eingebe,
funktioniert es aber nicht.
Hast Du eine Idee, was ich noch versuchen könnte?
Liebe Grüße
Denise

2013/11/30 Marco notifications@github.com

> Remember when we needed to ask in the places view if slug.nil?, to avoid
> the scary exception?
> Today we learn how to deal with this more gracefully (so it's not needed
> in the view), and more important "repair" the place data directly in case
> of an error.
> 
> some resources, in case you get stuck:
> - http://www.mikeperham.com/2012/03/03/the-perils-of-rescue-exception/
> - http://www.rubyinside.com/21-ruby-tricks-902.html
> 
> ## Have fun!
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/erdnusskeks/veganapp lesson_4
> 
> Or view, comment on, or merge it at:
> 
>   https://github.com/erdnusskeks/veganapp/pull/9
> Commit Summary
> - to_param when we have no slug
> 
> File Changes
> - _M_ spec/models/place_spec.rbhttps://github.com/erdnusskeks/veganapp/pull/9/files#diff-0(12)
> 
> Patch Links:
> - https://github.com/erdnusskeks/veganapp/pull/9.patch
> - https://github.com/erdnusskeks/veganapp/pull/9.diff

**Comment by DonSchado** [comment]
Hm... was passiert denn wenn du "bundle install" eingibst? 
Bekommst du da ne Fehlermeldung?

**Comment by erdnusskeks** [comment]
Ja, dann gibt's diese Fehlermeldung:

(...)
Installing psych (2.0.1)
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native
extension.

```
/Users/erdnusskeks/.rvm/rubies/ruby-1.9.3-p448/bin/ruby extconf.rb
```

checking for yaml.h... **\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
--with-opt-dir
--without-opt-dir
--with-opt-include
--without-opt-include=${opt-dir}/include
--with-opt-lib
--without-opt-lib=${opt-dir}/lib
--with-make-prog
--without-make-prog
--srcdir=.
--curdir
--ruby=/Users/erdnusskeks/.rvm/rubies/ruby-1.9.3-p448/bin/ruby
--with-libyaml-dir
--without-libyaml-dir
--with-libyaml-include
--without-libyaml-include=${libyaml-dir}/include
--with-libyaml-lib
--without-libyaml-lib=${libyaml-dir}/lib
--enable-bundled-libyaml
--disable-bundled-libyaml
/Users/erdnusskeks/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/mkmf.rb:381:in
`try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
from
/Users/erdnusskeks/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/mkmf.rb:506:in
`try_cpp'
from
/Users/erdnusskeks/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/mkmf.rb:970:in
`block in find_header'
from
/Users/erdnusskeks/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/mkmf.rb:790:in
`block in checking_for'
from
/Users/erdnusskeks/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/mkmf.rb:284:in
`block (2 levels) in postpone'
from
/Users/erdnusskeks/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/mkmf.rb:254:in
`open'
from
/Users/erdnusskeks/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/mkmf.rb:284:in
`block in postpone'
from
/Users/erdnusskeks/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/mkmf.rb:254:in
`open'
from
/Users/erdnusskeks/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/mkmf.rb:280:in
`postpone'
from
/Users/erdnusskeks/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/mkmf.rb:789:in
`checking_for'
from
/Users/erdnusskeks/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/mkmf.rb:969:in
`find_header'
from extconf.rb:9:in`<main>'

Gem files will remain installed in
/Users/erdnusskeks/.rvm/gems/ruby-1.9.3-p448/gems/psych-2.0.1 for
inspection.
Results logged to
/Users/erdnusskeks/.rvm/gems/ruby-1.9.3-p448/gems/psych-2.0.1/ext/psych/gem_make.out

An error occurred while installing psych (2.0.1), and Bundler cannot
continue.
Make sure that `gem install psych -v '2.0.1'` succeeds before bundling.

Hm...

2013/12/4 Marco notifications@github.com

**Comment by DonSchado** [comment]
ok, dann fliegt da der compiler ab, wegen irgendeiner Abhängigkeit die fehlt.
Können wir mal in Ruhe gemeinsam fixen.

Bis dahin nimm einfach psych aus dem Gemfile raus und bundle neu,
das sollte es für's erste beheben. 

(Das brauchen wir eigentlich eh nur für Heroku im Moment, 
also später drauf achten dass du die Änderungen am Gemfile und am Gemfile.lock nicht mit commitest.)

**Comment by erdnusskeks** [comment]
Ok, bevor ich hier was falsch machen: Wie genau gehe ich vor, um psych aus
dem Gemfile herauszunehmen? Wahrscheinlich übers Terminal, oder? Soll ja
nicht noch schlimmer werden... ; )
Liebe Grüße
Denise

Am 4. Dezember 2013 21:45 schrieb Marco notifications@github.com:

**Comment by DonSchado** [comment]
Ne, einfach das Projekt wie bisher mit Sublime öffnen und das Gemfile bearbeiten. 

Die Zeile mit gem "psych" löschen, 
speichern 
und danach im Terminal nochmal bundle install eingeben.

**Comment by DonSchado** [comment]
Bin mir nicht sicher ob wir hier fertig sind. :)
Vielleicht müssen wir da ansonsten später noch mal dran. Das 2-fache rescue ist schon unheimlich

**Comment by DonSchado** [comment]
ne ich glaub das lassen wir besser. :) 
Ich überleg mir was einfacheres und das hier mergen wir mal nicht.

**Pull request closed without merging**
